language: node_js

node_js: '12'

script:
  - npm run lint
  - npm run i18n:validate
  - npm run cofactsapi
  - npm run test -- --coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
