version: '2'
services:
  mongo-container:
    image: mongo:3.6
    container_name: mongodb
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root-test-password
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongo:/data/db"
    command: mongod

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server


  # Uncomment if you want to test your docker image locally
  #
  # rumors-line-bot:
  #   image: <your image hash>
  #   depends_on:
  #     - mongo-container
  #     - redis
  #   env_file:
  #     - .env
  #   ports:
  #     - "5001:5001"
